# INSECURE. Provided as an example only.
on:
  pull_request_target
  
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        #ref: ea2d3db900d77737dfed73d42e97998a8b58d2c8
    - name: Check PR title
      run: |
        title="${{ github.event.pull_request.title }}"
        if [[ $title =~ ^octocat ]]; then
        echo "PR title starts with 'octocat'"
        exit 0
        else
        echo "PR title did not start with 'octocat'"
        exit 1
        fi
